i3-msg 'rename workspace 1 to "1-Insomnia"'
i3-msg 'rename workspace 2 to "2-PyCharm"'
i3-msg 'rename workspace 3 to "3-GoogleChrome"'
i3-msg 'rename workspace 4 to "4-Notes"'
i3-msg 'rename workspace 5 to "5-Mail"'
